apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: syfo-migrering-altinn-lps
  namespace: team-esyfo
  labels:
    team: team-esyfo
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1  # Messages will never be deleted because of disk space
    retentionHours: -1  # Messages will never be timed  out
  acl:
    - team: team-esyfo
      application: syfooppfolgingsplanservice
      access: write
    - team: team-esyfo
      application: lps-oppfolgingsplan-mottak
      access: read

