apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: syfooppfolgingsplanservice-alerts
  namespace: default
  labels:
    team: teamsykefravr
spec:
  receivers:
    slack:
      channel: '#esyfo-alarm'
      prependText: '<!here> | '
  alerts:
    - alert: SYFOOPPFOLGINGSPLAN IS DOWN!
      expr: up{app="syfooppfolgingsplanservice", job="kubernetes-pods"} == 0
      for: 5m
      description: "App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}"
      action: "Undersøk hvofor {{ $labels.app }} er nede i prod-fss"
      severity: danger
    - alert: HIGH RATIO OF HTTP 5XX RESPONSE
      expr: (100 * (sum by (backend) (rate(traefik_backend_requests_total{code=~"^5\\d\\d", backend=~"syfooppfolgingsplanservice.nais.adeo..+"}[5m])) / sum by (backend) (rate(traefik_backend_requests_total{backend=~"syfooppfolgingsplanservice.nais.adeo..+"}[5m])))) > 2
      for: 5m
      description: "App {{ $labels.app }} har en høy andel 500 feil {{ $labels.kubernetes_namespace }}"
      action: "Sjekk i Grafana eller logger at {{ $labels.backend }} returnerer mange 500-feil"
      severity: danger
    - alert: HIGH RATIO OF HTTP 4XX RESPONSE
      expr: (100 * (sum by (backend) (rate(traefik_backend_requests_total{code=~"^4\\d\\d", backend=~"syfooppfolgingsplanservice.nais.adeo..+"}[5m])) / sum by (backend) (rate(traefik_backend_requests_total{backend=~"syfooppfolgingsplanservice.nais.adeo..+"}[5m])))) > 10
      for: 5m
      description: "App {{ $labels.app }} har en høy 400 feil {{ $labels.kubernetes_namespace }}"
      action: "Sjekk i Grafana eller logger at {{ $labels.backend }} returnerer mange 400-feil"
      severity: warning
