apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooppfolgingsplanservice
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  team: team-esyfo
  liveness:
    path: /syfooppfolgingsplanservice/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfooppfolgingsplanservice/internal/isReady
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 3060Mi
    requests:
      cpu: 1000m
      memory: 2048Mi
  replicas:
    min: 3
    max: 4
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /syfooppfolgingsplanservice/internal/prometheus
  ingresses:
    - "https://syfooppfolgingsplanservice.intern.nav.no"
    - "https://syfooppfolgingsplanservice.nais.adeo.no"
    - "https://app.adeo.no/syfooppfolgingsplanservice"
    - "https://syfooppfolgingsplanservice.prod-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: oppfolgingsplan-frontend
          namespace: team-esyfo
          cluster: prod-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: ditt-sykefravaer
          namespace: flex
          cluster: prod-gcp
    outbound:
      rules:
        - application: syfooppdfgen
          namespace: team-esyfo
          cluster: prod-gcp
  azure:
    application:
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://syfooppfolgingsplanservice.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/oracle/data/prod/creds/serviceoppfoelgingsdialog-user"
        mountPath: "/secrets/oppfolgingsplandb/credentials"
      - kvPath: "/oracle/data/prod/config/serviceoppfoelgingsdialog"
        mountPath: "/secrets/oppfolgingsplandb/config"
      - kvPath: "/kv/prod/fss/syfooppfolgingsplanservice/team-esyfo"
        mountPath: "/var/run/secrets/nais.io/vault"
  tokenx:
    enabled: true
  webproxy: true
  leaderElection: true
  envFrom:
    - configmap: loginservice-idporten
  kafka:
    pool: nav-prod
  env:
    - name: APP_NAME
      value: "syfooppfolgingsplanservice"
    - name: APPDYNAMICS_CONTROLLER_HOST_NAME
      value: appdynamics.adeo.no
    - name: APPDYNAMICS_CONTROLLER_PORT
      value: "443"
    - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
      value: "true"
    - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
      value: PROD
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: TJENESTER_URL
      value: https://tjenester.nav.no
    - name: DINE_SYKMELDTE_URL
      value: https://nav.no/arbeidsgiver/sykmeldte
    - name: EKSTERN_ALTINN_BEHANDLEALTINNMELDING_V1_ENDPOINTURL
      value: https://pep-gw.oera.no:9443/ekstern/altinn/BehandleAltinnMelding/v1
    - name: MQGATEWAY03_HOSTNAME
      value: a01apvl270.adeo.no
    - name: MQGATEWAY03_PORT
      value: "1414"
    - name: MQGATEWAY03_NAME
      value: MPLS03
    - name: SYFOOPPFOLGINGSPLANSERVICE_CHANNEL_NAME
      value: P_SYFOOPPFOLGINGSPL
    - name: VARSELPRODUKSJON_VARSLINGER_QUEUENAME
      value: QA.P_VARSELPRODUKSJON.SEND_VARSEL
    - name: VARSELPRODUKSJON_BEST_SRVMLD_M_KONTAKT_QUEUENAME
      value: QA.P_VARSELPRODUKSJON.BEST_SRVMLD_M_KONTAKT
    - name: LAGREJURIDISKLOGG_REST_URL
      value: https://app.adeo.no/juridisklogg/api/rest/logg
    - name: SYFOTILGANGSKONTROLL_CLIENT_ID
      value: "prod-fss.teamsykefravr.syfo-tilgangskontroll"
    - name: TILGANGSKONTROLLAPI_URL
      value: https://syfo-tilgangskontroll.nais.adeo.no/syfo-tilgangskontroll/api/tilgang
    - name: DOKARKIV_URL
      value: https://dokarkiv.nais.adeo.no
    - name: DKIF_URL
      value: https://dkif.intern.nav.no
    - name: CLIENT_ID
      value: 970b2069-0b53-492f-bd7a-acadfa211e9f
    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.adeo.no
    - name: AKTORREGISTER_REST_URL
      value: https://app.adeo.no/aktoerregister/api/v1
    - name: AAREG_SERVICES_URL
      value: https://aareg-services.intern.nav.no/api
    - name: EREG_BASEURL
      value: https://modapp.adeo.no
    - name: SYFOBRUKERTILGANG_URL
      value: https://syfobrukertilgang.nais.adeo.no
    - name: SYFOBRUKERTILGANG_ID
      value: prod-fss:team-esyfo:syfobrukertilgang
    - name: SYFOOPPDFGEN_URL
      value: https://syfooppdfgen.intern.nav.no
    - name: FELLESKODEVERK_URL
      value: https://kodeverk.nais.adeo.no/api/v1
    - name: SYFOSMREGISTER_URL
      value: https://smregister.intern.nav.no
    - name: SYFOSMREGISTER_ID
      value: prod-gcp:teamsykmelding:syfosmregister
    - name: NARMESTELEDER_URL
      value: https://narmesteleder.intern.nav.no
    - name: NARMESTELEDER_SCOPE
      value: api://prod-gcp.teamsykmelding.narmesteleder/.default
    - name: TOKENX_IDP
      value: https://oidc.difi.no/idporten-oidc-provider/
    - name: OPPFOLGINGSPLAN_FRONTEND_CLIENT_ID
      value: prod-gcp:team-esyfo:oppfolgingsplan-frontend
    - name: DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID
      value: prod-gcp:flex:ditt-sykefravaer
    - name: ISDIALOGMELDING_URL
      value: https://isdialogmelding.intern.nav.no
    - name: ISDIALOGMELDING_CLIENT_ID
      value: prod-gcp:teamsykefravr:isdialogmelding
    - name: ISDIALOGMELDING_AAD_CLIENT_ID
      value: prod-gcp.teamsykefravr.isdialogmelding
