apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: team-esyfo
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "999"
  name: syfooppfolgingsplanservice-redis
  namespace: team-esyfo
spec:
  image: redis:5-alpine
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
  service:
    port: 6379
