no.nav.security.oidc:
  issuers: selvbetjening,intern,veileder
  issuer:
    selvbetjening:
        discoveryurl: <naiserator>
        accepted_audience: <naiserator>
        cookie_name: selvbetjening-idtoken
    intern:
      discoveryurl: <naiserator>
      accepted_audience: modiabrukerdialog-p,modiabrukerdialog-q1,veilarblogin-p,veilarblogin-q1,fpsak-frontend-p,fpsak-frontend-q1,fplos-p,fplos-q1
      cookie_name: ID_token
    veileder:
      discoveryurl: <naiserator>
      accepted_audience: <naiserator>
      cookie_name: isso-idtoken

logging.config: classpath:logback-spring.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

server:
  servlet:
    context-path: /syfooppfolgingsplanservice

spring:
  main.banner-mode: 'off'
  cache.type: redis
  redis:
    host: syfooppfolgingsplanservice-redis
    port: 6379
  jta.atomikos.datasource:
    max-pool-size: 32
    min-pool-size: 8

dev: false
