no.nav.security.jwt:
  issuer:
    selvbetjening:
      discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
      accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
      cookiename: selvbetjening-idtoken
    internazureadv2:
      discoveryurl: ${azure.app.well.known.url}
      accepted_audience: ${azure.app.client.id}
      cookiename: ID_token
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
      proxyurl: ${?NO_PROXY}

logging.config: classpath:logback-spring.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

server:
  servlet:
    context-path: /syfooppfolgingsplanservice

spring:
  main.banner-mode: 'off'
  cache.type: redis
  redis:
    host: syfooppfolgingsplanservice-redis
    port: 6379
  jta.atomikos.datasource:
    max-pool-size: 32
    min-pool-size: 8

dev: false
