no.nav.security.jwt:
  issuer:
    internazureadv2:
      discoveryurl: ${azure.app.well.known.url}
      accepted_audience: ${azure.app.client.id}
      cookiename: ID_token
      proxy-url: http://webproxy.nais:8088
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}

logging.config: classpath:logback-spring.xml

management:
  endpoint.prometheus.enabled: true
  endpoints.web:
    base-path: /internal
    exposure.include: prometheus
    path-mapping.prometheus: /prometheus

server:
  servlet:
    context-path: /syfooppfolgingsplanservice

spring:
  main.banner-mode: 'off'
  cache.type: redis
  data:
    redis:
      host: syfooppfolgingsplanservice-redis
      port: 6379
  jta.atomikos:
    datasource:
      max-pool-size: 32
      min-pool-size: 8
    properties:
      default-jta-timeout: 15000
dev: false
