-- ROLLBACK-START
------------------
-- DROP SEQUENCE TILBAKEMELDING_ID_SEQ;
-- DROP TABLE TILBAKEMELDING;
---------------
-- ROLLBACK-END


CREATE SEQUENCE TILBAKEMELDING_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE TILBAKEMELDING (
  tilbakemelding_id     NUMBER(19, 0) NOT NULL,
  oppfoelgingsdialog_id NUMBER(19, 0) NOT NULL,
  aktoer_id             VARCHAR(13)   NOT NULL,
  beskrivelse           VARCHAR(1200) NOT NULL,
  CONSTRAINT TILBAKEMELDING_PK PRIMARY KEY (tilbakemelding_id),
  CONSTRAINT TILBAKEMELDING_PLAN_FK FOREIGN KEY (oppfoelgingsdialog_id) REFERENCES OPPFOELGINGSDIALOG (oppfoelgingsdialog_id)
);