apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: syfooppfolgingsplanservice-alerts
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  groups:
    - name: syfooppfolgingsplanservice-alerts
      rules:
        - alert: SYFOOPPFOLGINGSPLAN IS DOWN!
          expr: kube_deployment_status_replicas_available{deployment="syfooppfolgingsplanservice"} == 0
          for: 5m
          annotations:
            summary: "syfooppfolgingsplanservice er nede"
            action: "Undersøk hvorfor syfooppfolgingsplanservice er nede"
          labels:
            namespace: team-esyfo
            severity: critical
        - alert: HIGH RATIO OF HTTP 5XX RESPONSE
          expr: (100 * (sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", status=~"^5\\d\\d", service="syfooppfolgingsplanservice"}[5m]))) / (sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", service="syfooppfolgingsplanservice"}[5m])))) > 2
          for: 5m
          annotations:
            summary: "syfooppfolgingsplanservice har en høy andel 500 feil"
            action: "Sjekk i Grafana eller logger hvorfor syfooppfolgingsplanservice returnerer mange 500-feil"
          labels:
            namespace: team-esyfo
            severity: warning
        - alert: HIGH RATIO OF HTTP 4XX RESPONSE
          expr: (100 * (sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", status=~"^4\\d\\d", service="syfooppfolgingsplanservice"}[5m]))) / (sum by (backend) (rate(nginx_ingress_controller_requests{namespace="team-esyfo", service="syfooppfolgingsplanservice"}[5m])))) > 10
          for: 5m
          annotations:
            summary: "syfooppfolgingsplanservice har en høy andel 400 feil"
            action: "Sjekk i Grafana eller logger hvorfor syfooppfolgingsplanservice returnerer mange 400-feil"
          labels:
            namespace: team-esyfo
            severity: warning
