apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfooppfolgingsplanservice
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /syfooppfolgingsplanservice/internal/isAlive
    initialDelay: 60
    timeout: 1
    periodSeconds: 10
    failureThreshold: 5
  readiness:
    path: /syfooppfolgingsplanservice/internal/isReady
    initialDelay: 60
    timeout: 1
  resources:
    limits:
      cpu: 3000m
      memory: 3060Mi
    requests:
      cpu: 1000m
      memory: 2048Mi
  replicas:
    min: 3
    max: 4
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /syfooppfolgingsplanservice/internal/prometheus
  ingresses:
    - "https://syfooppfolgingsplanservice.intern.nav.no"
    - "https://syfooppfolgingsplanservice.nais.adeo.no"
    - "https://app.adeo.no/syfooppfolgingsplanservice"
    - "https://syfooppfolgingsplanservice.prod-fss-pub.nais.io"
  accessPolicy:
    inbound:
      rules:
        - application: oppfolgingsplan-frontend
          namespace: team-esyfo
          cluster: prod-gcp
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-fss
        - application: syfomodiaperson
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: ditt-sykefravaer
          namespace: flex
          cluster: prod-gcp
    outbound:
      rules:
        - application: syfooppdfgen
          namespace: team-esyfo
          cluster: prod-gcp
        - application: istilgangskontroll
          namespace: teamsykefravr
          cluster: prod-gcp
        - application: syfobrukertilgang
          namespace: team-esyfo
          cluster: prod-gcp
      external:
        - host: digdir-krr-proxy.intern.nav.no
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
      replyURLs:
        - "https://syfooppfolgingsplanservice.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  vault:
    enabled: true
    paths:
      - kvPath: "/oracle/data/prod/creds/serviceoppfoelgingsdialog-user"
        mountPath: "/secrets/oppfolgingsplandb/credentials"
      - kvPath: "/oracle/data/prod/config/serviceoppfoelgingsdialog"
        mountPath: "/secrets/oppfolgingsplandb/config"
      - kvPath: "/kv/prod/fss/syfooppfolgingsplanservice/team-esyfo"
        mountPath: "/var/run/secrets/nais.io/vault"
  tokenx:
    enabled: true
  leaderElection: true
  kafka:
    pool: nav-prod
  env:
    - name: ENVIRONMENT
      value: prod
    - name: APP_NAME
      value: "syfooppfolgingsplanservice"
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    - name: TJENESTER_URL
      value: https://tjenester.nav.no
    - name: DINE_SYKMELDTE_URL
      value: https://nav.no/arbeidsgiver/sykmeldte
    - name: EKSTERN_ALTINN_BEHANDLEALTINNMELDING_V1_ENDPOINTURL
      value: https://pep-gw.oera.no:9443/ekstern/altinn/BehandleAltinnMelding/v1
    - name: LAGREJURIDISKLOGG_REST_URL
      value: https://app.adeo.no/juridisklogg/api/rest/logg
    - name: ISTILGANGSKONTROLL_CLIENT_ID
      value: prod-gcp.teamsykefravr.istilgangskontroll
    - name: ISTILGANGSKONTROLL_URL
      value: https://istilgangskontroll.intern.nav.no
    - name: DOKARKIV_URL
      value: https://dokarkiv.nais.adeo.no
    - name: DKIF_URL
      value: https://digdir-krr-proxy.intern.nav.no/rest/v1/personer
    - name: DKIF_SCOPE
      value: api://prod-gcp.team-rocket.digdir-krr-proxy/.default
    - name: CLIENT_ID
      value: 970b2069-0b53-492f-bd7a-acadfa211e9f
    - name: PDL_URL
      value: https://pdl-api.nais.adeo.no/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: SECURITY_TOKEN_SERVICE_REST_URL
      value: https://security-token-service.nais.adeo.no
    - name: AAREG_SERVICES_URL
      value: https://aareg-services.intern.nav.no/api
    - name: AAREG_SCOPE
      value: api://prod-fss.arbeidsforhold.aareg-services-nais/.default
    - name: EREG_BASEURL
      value: https://ereg-services.intern.nav.no
    - name: SYFOBRUKERTILGANG_URL
      value: https://syfobrukertilgang.intern.nav.no
    - name: SYFOBRUKERTILGANG_ID
      value: prod-gcp:team-esyfo:syfobrukertilgang
    - name: SYFOOPPDFGEN_URL
      value: https://syfooppdfgen.intern.nav.no
    - name: FELLESKODEVERK_URL
      value: https://kodeverk-api.nav.no/api/v1
    - name: FELLESKODEVERK_SCOPE
      value: api://prod-gcp.team-rocket.kodeverk-api/.default
    - name: SYFOSMREGISTER_URL
      value: https://smregister.intern.nav.no
    - name: SYFOSMREGISTER_ID
      value: prod-gcp:teamsykmelding:syfosmregister
    - name: NARMESTELEDER_URL
      value: https://narmesteleder.intern.nav.no
    - name: NARMESTELEDER_SCOPE
      value: api://prod-gcp.teamsykmelding.narmesteleder/.default
    - name: OPPFOLGINGSPLAN_FRONTEND_CLIENT_ID
      value: prod-gcp:team-esyfo:oppfolgingsplan-frontend
    - name: DITT_SYKEFRAVAER_FRONTEND_CLIENT_ID
      value: prod-gcp:flex:ditt-sykefravaer
    - name: ISDIALOGMELDING_URL
      value: https://isdialogmelding.intern.nav.no
    - name: ISDIALOGMELDING_CLIENT_ID
      value: prod-gcp:teamsykefravr:isdialogmelding
    - name: ISDIALOGMELDING_AAD_CLIENT_ID
      value: prod-gcp.teamsykefravr.isdialogmelding
    - name: DISTRIBUTE_ALTINN_PLANS
      value: "false"
