ALTER TABLE ARBEIDSOPPGAVE
  DROP COLUMN KAN_GJENNOMF_TILRETTELEGGING;
ALTER TABLE ARBEIDSOPPGAVE
  DROP COLUMN KAN_IKKE_GJENNOMFOERES;
ALTER TABLE ARBEIDSOPPGAVE
  DROP COLUMN KAN_GJENNOMFOERES_NORMALT;