-- ROLLBACK-START
------------------
-- ALTER TABLE OPPFOLGINGSPLANLPS DROP ( JOURNALPOST_ID );
---------------
-- ROLLBACK-END

ALTER TABLE OPPFOLGINGSPLANLPS
  ADD (
  JOURNALPOST_ID VARCHAR(20)
  );
