-- ROLLBACK-START
------------------
-- DROP TABLE OPPFOELGINGSDIALOG DROP COLUMN arbeidsgiver_sist_aksessert;
-- DROP TABLE OPPFOELGINGSDIALOG DROP COLUMN sykmeldt_sist_aksessert;
-- DROP TABLE OPPFOELGINGSDIALOG DROP COLUMN arbeidsgiver_sist_endret;
-- DROP TABLE OPPFOELGINGSDIALOG DROP COLUMN sykmeldt_sist_endret;

---------------
-- ROLLBACK-END

ALTER TABLE OPPFOELGINGSDIALOG
  ADD (
  ARBEIDSGIVER_SIST_AKSESSERT TIMESTAMP,
  SYKMELDT_SIST_AKSESSERT TIMESTAMP,
  ARBEIDSGIVER_SIST_ENDRET TIMESTAMP,
  SYKMELDT_SIST_ENDRET TIMESTAMP
  );



