-- ROLLBACK-START
------------------
-- ALTER TABLE OPPFOLGINGSPLANLPS DROP ( ARCHIVE_REFERENCE );
---------------
-- ROLLBACK-END

ALTER TABLE OPPFOLGINGSPLANLPS
  ADD (
    ARCHIVE_REFERENCE VARCHAR(40) DEFAULT '<NA>' NOT NULL
  );
