-- ROLLBACK-START
------------------
-- ALTER TABLE GODKJENTPLAN DROP ( SAK_ID, JOURNALPOST_ID );
---------------
-- ROLLBACK-END

ALTER TABLE GODKJENTPLAN
  ADD (
  SAK_ID VARCHAR(20),
  JOURNALPOST_ID VARCHAR(20)
  );
