
-- SLETTE EVT. DOBLE FOREKOMSTER AV GODKJENT PLAN
DELETE FROM
  GODKJENTPLAN A
WHERE
  a.rowid !=
  ANY (
    SELECT
      B.rowid
    FROM
      GODKJENTPLAN B
    WHERE
      A.OPPFOELGINGSDIALOG_ID = B.OPPFOELGINGSDIALOG_ID
      AND
      A.GODKJENTPLAN_ID > B.GODKJENTPLAN_ID
  );

ALTER TABLE GODKJENTPLAN
ADD UNIQUE (
  OPPFOELGINGSDIALOG_ID
  );

DROP SEQUENCE SAMTYKKE_ID_SEQ;
DROP TABLE SAMTYKKE;

CREATE INDEX oppdialog_aktoerid_index ON OPPFOELGINGSDIALOG (AKTOER_ID);
CREATE INDEX tiltak_oppdialogid_index ON TILTAK (OPPFOELGINGSDIALOG_ID);
CREATE INDEX arboppg_oppdialogid_index ON ARBEIDSOPPGAVE (OPPFOELGINGSDIALOG_ID);
CREATE INDEX godkj_oppdialogid_index ON GODKJENNING (OPPFOELGINGSDIALOG_ID);