apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-syfo-oppfolgingsplan-lps-nav-v2
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  pool: {{kafkaPool}}
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3
    retentionBytes: -1  # Messages will never be deleted because of disk space
    retentionHours: -1  # Messages will never be timed out
  acl:
    - team: team-esyfo
      application: syfooppfolgingsplanservice
      access: write
    - team: teamsykefravr
      application: ispersonoppgave
      access: read
