name: Build & Deploy
on:
  push:
  workflow_dispatch:

jobs:
  jar-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/fss-boot-jar-app.yaml@use-java-21-for-fss
    permissions:
      actions: read
      contents: write
      security-events: write
      packages: write
      id-token: write
    secrets: inherit
    with:
      app: syfooppfolgingsplanservice
