name: run-build-and-generate-dependency-snapshot

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate # Only generate in this job
      - name: Run a build, generating the dependency graph snapshot which will be submitted
        run: ./gradlew dependencies --configuration runtimeClasspath