name: Deploy redis to NAIS
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/redis.yaml'
      - 'redis-config.yaml'
jobs:
  apply-redis:
    name: Apply Redis cache to cluster
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: redis-config.yaml
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: redis-config.yaml
